server:
    port: 8030    
    # servlet:
    #     context-path: /api/v1/data
application:
    timezone: America/Sao_Paulo
spring:
    profiles:
        default: dev
        active: ${SPRING_ACTIVE_PROFILE:default}
    webflux:
        base-path: /api/v1/data
    application:
        name: ofx-ms-data
    rabbitmq:
        host: ${conf.rabbit.host}
        port: ${conf.rabbit.port}
        username: ${conf.rabbit.user}
        password: ${conf.rabbit.pass}
    r2dbc:
        url: r2dbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
        username: ${conf.db.user}
        password: ${conf.db.pass}
    datasource:
        jpa:
            url: jdbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
            username: ${conf.db.user}
            password: ${conf.db.pass}
            driver-class-name: org.postgresql.Driver
        r2dbc:
            url: r2dbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
            username: ${conf.db.user}
            password: ${conf.db.pass}
            driver: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    flyway:
        # enabled: true
        user: ${conf.db.user}
        password: ${conf.db.pass}
        schemas: public
        url: jdbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
        # locations: filesystem:resources/db/${POSTGRESQL_USER}
    main:
        web-application-type: reactive
    cloud:
        openfeign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: basic
                    permission-checker:
                        url: ${conf.permission-checker.url}
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: full
queue:
    name: 
        sse: sse.queue
        imported: imported.queue
    routing-key:
        sse: sse
        imported: imported
exchange:
    name: ofx.app