conf:
    db:
        host: 
        port: 0
        database: ofxmsdata
        user: sa
        pass: password
    permission-checker:
        url: http://localhost:8050/api/v1/permission-checker
    rabbit:
        host: rabbitmq
        port: 5672
        user: admin
        pass: admin

spring:
    h2:
        console.enabled: true
    r2dbc:
        url: r2dbc:h2:mem:///${conf.db.database}
        username: ${conf.db.user}
        password: ${conf.db.pass}
    datasource:
        jpa:
            url: jdbc:h2:mem:///${conf.db.database}
            username: ${conf.db.user}
            password: ${conf.db.pass}
            driver-class-name: org.h2.Driver
        r2dbc:
            url: r2dbc:h2:mem:///${conf.db.database}
            username: ${conf.db.user}
            password: ${conf.db.pass}
            driver: h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
    flyway:
        user: ${conf.db.user}
        password: ${conf.db.pass}
        schemas: public
        url: jdbc:h2:mem:${conf.db.database}
    main:
        web-application-type: reactive
    cloud:
        openfeign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: basic
                    permission-checker:
                        url: ${conf.permission-checker.url}
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: full
queue:
    name: 
        sse: sse.queue
        imported: imported.queue
    routing-key:
        sse: sse
        imported: imported
exchange:
    name: ofx.app