CREATE TABLE IF NOT EXISTS CONTA_BANCARIA (
   ID BIGINT NOT NULL PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   NUMERO VARCHAR(15) NOT NULL,
   BANCO VARCHAR(100),
   COR VARCHAR(100),
   ID_UE BIGINT REFERENCES UNIDADE_ECONOMICA(ID) NOT NULL,
   STATUS VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS contabancaria_idue_idx on CONTA_BANCARIA (id_ue);
CREATE INDEX IF NOT EXISTS contabancaria_status_idx on CONTA_BANCARIA (status);
