CREATE TABLE IF NOT EXISTS IMPORTACAO (
   ID BIGSERIAL NOT NULL PRIMARY KEY,
   ID_USER BIGINT NOT NULL REFERENCES OFX_USER(ID),
   ID_USER_IMPORTADOR BIGINT NOT NULL REFERENCES OFX_USER(ID),
   ID_UE BIGINT REFERENCES UNIDADE_ECONOMICA(ID),
   ID_CONTA_BANCARIA BIGINT REFERENCES CONTA_BANCARIA(ID),
   DATA_IMPORTACAO TIMESTAMP WITH TIME ZONE NOT NULL,
   NOME_ARQUIVO VARCHAR(500) NOT NULL,
   NR_REGISTROS INTEGER NOT NULL,
   STATUS VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS importacao_iduser_idx on IMPORTACAO (id_user);
CREATE INDEX IF NOT EXISTS importacao_iduserimportador_idx on IMPORTACAO (id_user_importador);
CREATE INDEX IF NOT EXISTS importacao_idue_idx on IMPORTACAO (id_ue);
CREATE INDEX IF NOT EXISTS importacao_idcontabancaria_idx on IMPORTACAO (id_conta_bancaria);
CREATE INDEX IF NOT EXISTS importacao_status_idx on IMPORTACAO (status);
CREATE INDEX IF NOT EXISTS importacao_dataimportacao_idx on IMPORTACAO (data_importacao);