CREATE TABLE IF NOT EXISTS OPERACAO (
   ID BIGSERIAL NOT NULL PRIMARY KEY,
   ID_USER BIGINT NOT NULL REFERENCES OFX_USER(ID),
   ID_UE BIGINT REFERENCES UNIDADE_ECONOMICA(ID),
   ID_CONTA_BANCARIA BIGINT REFERENCES CONTA_BANCARIA(ID),
   ID_IMPORTACAO BIGINT REFERENCES IMPORTACAO(ID),
   TIPO VARCHAR(20) NOT NULL,
   DATA_HORA TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   VALOR NUMERIC(16,2) NOT NULL,
   FIT_ID VARCHAR NOT NULL,
   REF_NUM VARCHAR,
   MEMO VARCHAR NOT NULL,   
   STATUS VARCHAR(20) NOT NULL,
   ORDEM INTEGER NOT NULL DEFAULT 0,
   ID_GRUPO BIGINT REFERENCES OPERACAO(ID)
);

CREATE INDEX IF NOT EXISTS operacao_iduser_idx on OPERACAO (id_user);
CREATE INDEX IF NOT EXISTS operacao_idue_idx on OPERACAO (id_ue);
CREATE INDEX IF NOT EXISTS operacao_idcontabancaria_idx on OPERACAO (id_conta_bancaria);
CREATE INDEX IF NOT EXISTS operacao_idimportacao_idx on OPERACAO (id_importacao);
CREATE INDEX IF NOT EXISTS operacao_fitid_idx on OPERACAO (fit_id);
CREATE INDEX IF NOT EXISTS operacao_status_idx on OPERACAO (status);
CREATE INDEX IF NOT EXISTS operacao_grupoid_idx on OPERACAO (id_grupo);